# Generated by Django 3.0.5 on 2020-04-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('userProvider', models.CharField(blank=True, max_length=255)),
                ('phoneProvider', models.CharField(blank=True, max_length=255)),
                ('emailProvider', models.EmailField(blank=True, max_length=255)),
            ],
        ),
    ]
