# Generated by Django 3.0.5 on 2020-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phoneProvider',
            field=models.BigIntegerField(blank=True),
        ),
    ]
