# Generated by Django 3.0.5 on 2020-04-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
