# Generated by Django 3.0.5 on 2020-04-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200409_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
