# Generated by Django 3.0.5 on 2020-04-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_products'),
        ('products', '0003_auto_20200407_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='branches.Branch'),
        ),
    ]
