# Generated by Django 3.0.5 on 2020-04-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('providers', '0001_initial'),
        ('products', '0006_auto_20200411_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='providers.Provider'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.Category'),
        ),
    ]
