# Generated by Django 3.0.5 on 2020-04-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200414_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='observations',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
