# Generated by Django 3.0.3 on 2020-02-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='nombre',
            field=models.CharField(default='branch', max_length=15),
            preserve_default=False,
        ),
    ]
