# Generated by Django 3.0.3 on 2020-02-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='nombre',
            new_name='name',
        ),
    ]
